PDEP Decision Making
noatamir/pandas pull request #2
Opened 2023-05-03 15:45 UTC by noatamir

The governance working group has been discussing the PDEP workflow and decision-making for some time now.

This PR proposes some formulation of the existing workflow to clarify and facilitate it for current and future authors, and voting members.  
In our discussions, we assessed that a more structured process would help folks who submit the PDEP know how and when it can progress, and how to better engage with others.

The timelines were considered to facilitate an engaging discussion, and automation. We aim to make the lives of the PDEP authors easier by taking away the need to decide "has it been long enough", or "cat herding" folks to engage and clarify their comments so that PDEPs don't get large change requests that could have been clarified early on - late in the process.

We tried to make things as flexible and clear as possible. Being mindful of the needs of the authors, as well as those engaging in the discussion, be them voting members or not.

At this point, we would like to invite feedback. It might be that you need more clarity on the suggestions, have ideas for improvement, or aren't convinced that this will affect the current process positively.

2023-05-03 15:51 UTC, jorisvandenbossche commented on web/pandas/pdeps/0001-purpose-and-guidelines.md
> +The initial status of a PDEP will be `Status: Draft`. This will be changed to
A little bit up, in the list of possible states, we should probably add "Draft"?

2023-05-03 15:57 UTC, jorisvandenbossche commented
NEP and SLEP 0 both have the following paragraph:

> In general, the goal is to make sure that the community has consensus, not provide a rigid policy for people to try to game. When in doubt, err on the side of asking for more feedback and looking for opportunities to compromise.

I think I would prefer to include something like that as well here

2023-05-03 15:59 UTC, jorisvandenbossche commented on web/pandas/pdeps/0001-purpose-and-guidelines.md
> +
Could we have a subsection "How a PDEP becomes Accepted" (or different title), and then having schedule/voting/quorum be subsection of this one?

2023-05-03 16:27 UTC, Dr-Irv requested changes
as discussed in governance meeting, add an introductory paragraph to the Workflow section that indicates the rationale for the process.

2023-05-03 16:34 UTC, Dr-Irv requested changes
small changes to create section headers

2023-05-03 16:34 UTC, Dr-Irv commented on web/pandas/pdeps/0001-purpose-and-guidelines.md
> +Our workflow was created to support and enable a consensus seeking process, and to provide clarify,
make this subsection `#### Rationale`

2023-05-03 16:34 UTC, Dr-Irv commented on web/pandas/pdeps/0001-purpose-and-guidelines.md
>  The possible states of a PDEP are:
Make this a subsection `#### PDEP States`

2023-05-10 07:41 UTC, noatamir commented on web/pandas/pdeps/0001-purpose-and-guidelines.md
> +
I find this a bit redundant as this is all under the PDEP workflow, and it just makes the following sections be on a different level which bugs me somehow(?!). I tried renaming a few of the subsections to increase clarify. Please let me know if you still think this is needed.

2023-07-09 22:23 UTC, closed without merging